#%RAML 1.0
title: Inventory API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Batch API"
    content: <b>API for interacting with an inventory of physical resources</b>

types:
  instances: !include instances.json
  instancesBatchResponse: !include instances-batch-response.json

/inventory/instances/batch:
  displayName: Instances batch API
  post:
    description: "Create collection of instances in one request"
    body:
      application/json:
        type: instances
    responses:
      201:
        description: "Instances are created"
        body:
          application/json:
            type: instancesBatchResponse
      500:
        description: "Internal server error"
        body:
          application/json:
            type: instancesBatchResponse
