#%RAML 1.0
title: Inventory Event Handlers API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory Event Handlers API"
    content: <b>API for handling events</b>

/inventory/handlers:
  /instances:
    displayName: API for handling Instance update events
    post:
      description: "Handler for Instance update events"
      body:
        application/json:
      responses:
        204:
          description: "Received event"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
