#%RAML 1.0
title: Inventory Event Handlers API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory Event Handlers API"
    content: <b>API for handling events</b>

/inventory/handlers/data-import:
  displayName: API for handling all data-import events
  post:
    description: "Handler for data-import events"
    body:
      application/json:
    responses:
      204:
        description: "Received data-import event"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
