package org.folio.inventory.dataimport.handlers;

public enum QMEventTypes {

  QM_SRS_MARC_RECORD_UPDATED,
  QM_ERROR,
  QM_INVENTORY_INSTANCE_UPDATED,
  QM_INVENTORY_HOLDINGS_UPDATED,
  QM_INVENTORY_AUTHORITY_UPDATED
}
